version: "3"
services:
  # mecanicaz-db:
  #     image: postgres:12.0
  #     restart: always
  #     ports:
  #       - ${DB_PORT}:${DB_PORT}
  #     environment:
  #       POSTGRES_PASSWORD: ${DB_PASSWORD}
  #       POSTGRES_USER: ${DB_USER}
  #       POSTGRES_DB: ${PRISMA_SERVICE}
  mecanicaz-db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - ${PRISMA_PORT}:${PRISMA_PORT}
    environment:
      # PRISMA_HOST: 
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: ${PRISMA_PORT}
        databases:
          default:
            database: ${PRISMA_SERVICE}
            #connector: postgres
            connector: mysql
            host: mecanicaz-db
            port: ${DB_PORT}
            user: ${DB_USER}
            password: ${DB_PASSWORD}
            migrations: true